config/routes.rb
Rails.application.routes.draw do
  root 'application#root'
  get '/colors', constraints: { format: 'json' }, to: 'application#colors'

  resources :meats do
    collection do
      get :tuples, constraints: { format: 'json' }
    end
  end

  resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/filling.rb
class Filling < ApplicationRecord
  has_many :orders, dependent: :nullify

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: true
  validates :calories, presence: true, numericality: true
end

app/models/meat.rb
class Meat < ApplicationRecord
  has_many :orders, dependent: :nullify

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: true
  validates :calories, presence: true, numericality: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :meat, optional: true

  BEANS = %w[Black Pinto None].freeze
  RICE = %w[White Brown None].freeze
  TORTILLAS = %w[Corn Flour Wheat None].freeze

  TOPPINGS_ATTRS = %w[cheese lettuce guacamole salsa sour_cream].freeze

  validates :name_first, presence: true
  validates :name_last, presence: true

  validates :beans, inclusion: BEANS, allow_nil: true
  validates :rice, inclusion: RICE, allow_nil: true
  validates :tortilla, inclusion: TORTILLAS, allow_nil: true

  # Need valid address on delivery orders
  validates(:address_street1,
            :address_zip,
            :address_city,
            :address_state,
            presence: true,
            if: :delivery)

  #
  # toppings accessors
  #

  # toppings as array of strings
  def toppings
    TOPPINGS_ATTRS.select { self[_1] }.map(&:titleize).sort
  end

  # set toppings as an array of strings
  def toppings=(arr)
    arr = (arr || []).map { _1.parameterize(separator: '_') }
    TOPPINGS_ATTRS.each { self[_1] = arr.include?(_1) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def colors
    render json: Color::COLORS
  end
end

app/controllers/meats_controller.rb
class MeatsController < ApplicationController
  before_action :set_meat, only: %i[show edit update destroy]

  # CSRF tokens don't work properly in the replit webview iframe
  skip_before_action :verify_authenticity_token

  # GET /meats or /meats.json
  def index
    @meats = Meat.all.order(:name)
  end

  def tuples
    @meats = Meat.where(available: true).order(:name)
  end

  # GET /meats/1 or /meats/1.json
  def show; end

  # GET /meats/new
  def new
    @meat = Meat.new
  end

  # GET /meats/1/edit
  def edit; end

  # POST /meats or /meats.json
  def create
    @meat = Meat.new(meat_params)

    respond_to do |format|
      if @meat.save
        format.html { redirect_to meats_url, notice: 'Meat was successfully created.' }
        format.json { render :show, status: :created, location: @meat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meats/1 or /meats/1.json
  def update
    respond_to do |format|
      if @meat.update(meat_params)
        format.html { redirect_to meats_url, notice: 'Meat was successfully updated.' }
        format.json { render :show, status: :ok, location: @meat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meats/1 or /meats/1.json
  def destroy
    @meat.destroy

    respond_to do |format|
      format.html { redirect_to meats_url, notice: 'Meat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meat
    @meat = Meat.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def meat_params
    params.require(:meat).permit(:name, :description, :price, :calories, :available)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[show edit update destroy]

  # CSRF tokens don't work properly in the replit webview iframe
  skip_before_action :verify_authenticity_token

  # GET /orders or /orders.json
  def index
    @orders = Order.all.order(created_at: :desc)
  end

  # GET /orders/1 or /orders/1.json
  def show; end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit; end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url, notice: 'We got your order. Thanks!' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to orders_url, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def order_params
    params.require(:order).permit(
      :beans,
      :address_city,
      :address_state,
      :address_street1,
      :address_street2,
      :address_zip,
      :delivery,
      :email,
      :favorite_color,
      :meat_id,
      :instructions,
      :name_first,
      :name_last,
      :phone,
      :rice,
      :tortilla,
      toppings: []
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Wrapper around form_with that automatically populates some data attributes:
  #   - data-lob-mangle
  #   - data-lob-values
  #   - data-lob-errors
  #
  # Example usage:
  #   lob_form_with(
  #     model: model,
  #     data: { lob: 'abc123' },
  #     html: { style: 'min-height:400px' }
  #   ) {} %>
  #
  def lob_form_with(model: nil, scope: nil, url: nil, format: nil, **options, &block)
    scope_for_mangle = scope

    if model
      model = model.is_a?(Array) ? model.last : model
      scope_for_mangle ||= model_name_from_record_or_class(model).param_key
    end

    # Add default options
    options = options.dup
    options[:data] = (options[:data] || {}).with_indifferent_access.tap do |data|
      data[:'lob-mangle'] ||= "#{scope_for_mangle}[$name]"
      if model
        data[:'lob-values'] ||= model.as_json
        data[:'lob-errors'] = model.errors.map { { name: _1.attribute, message: _1.full_message } }
      end
    end

    form_with(model: model, scope: scope, url: url, format: format, **options, &block)
  end
end

app/helpers/meats_helper.rb
module MeatsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/application/root.html.erb
<div class="application_root">
  <div class="customers">
    <% if notice.present? %>
      <p style="color: green"><%= notice %></p>
    <% end %>
    <%= image_tag("crown.svg", class: "logo") %>
    <h1>Burrito King</h1>
    <%= link_to("Place an order", new_order_path, class: "order") %>
  </div>

  <div class="employees">
    <h2>Employees Only</h2>
    <ul>
      <li><%= link_to("Edit menu", meats_path) %></li>
      <li><%= link_to("View orders", orders_path) %></li>
    </ul>
  </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Burrito King</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <% if !current_page?(root_path) %>
      <div class="navbar">
        <a class="link-home" href="/">
          <%= image_tag("crown.svg", class: "logo") %>
          <div>Burrito King</div>
        </a>
      </div>
    <% end %>

    <div class="main-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/meats/_form.html.erb
<%= form_with(model: meat) do |form| %>
  <div>TODO: replace this with your form</div>
<% end %>

app/views/meats/_meat.html.erb
<div id="<%= dom_id meat %>">
 <%= meat.name %> ($<%= meat.price %>)
 <% if !meat.available %>
   - out of stock
 <% end %>

</div>

app/views/meats/edit.html.erb
<h1>Editing meat</h1>

<%= render "form", meat: @meat %>

<br>

<div>
  <%= link_to "Back to meats", meats_path %>
</div>

<br>

<div>
  <%= button_to "Destroy this meat", @meat, method: :delete %>
</div>

app/views/meats/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Meats</h1>

<% if @meats.length > 0 %>
  <table id="meats">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Calories</th>
      <th>Available</th>
    </tr>

    <% @meats.each do |meat| %>
      <tr>
        <td><%= link_to(meat.name, edit_meat_path(meat)) %></td>
        <td><%= truncate(meat.description, length: 50) %></td>
        <td><%= number_to_currency(meat.price) %></td>
        <td><%= meat.calories %></td>
        <td><%= meat.available ? "yes" : "no" %></td>
      </tr>
    <% end %>
  </table>
<% end %>

<%= link_to "New meat", new_meat_path %>

app/views/meats/new.html.erb
<h1>New meat</h1>

<%= render "form", meat: @meat %>

<br>

<div>
  <%= link_to "Back to meats", meats_path %>
</div>

app/views/meats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @meat %>

<div>
  <%= link_to "Edit this meat", edit_meat_path(@meat) %> |
  <%= link_to "Back to meats", meats_path %>
</div>

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <div>TODO: replace this with your form</div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  Name: <%= order.name_first %> <%= order.name_last %>
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

<br>

<div>
  <%= button_to "Destroy this order", @order, method: :delete %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<% if @orders.length > 0 %>
  <table id="orders">
    <tr>
      <th>Created</th>
      <th>Customer</th>
      <th>Tortilla</th>
      <th>Rice</th>
      <th>Beans</th>
      <th>Meat</th>
      <th>Delivery</th>
    </tr>

    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to(order.created_at, edit_order_path(order)) %></td>
        <td>
          <%= truncate("#{order.name_first} #{order.name_last}", length: 80) %>
        </td>
        <td><%= order.tortilla %></td>
        <td><%= order.rice %></td>
        <td><%= order.beans %></td>
        <td><%= order.meat&.name %></td>
        <td><%= order.delivery ? "yes" : "no" %></td>
      </tr>
    <% end %>
  </table>
<% end %>

<%= link_to "New order", new_order_path %>

app/views/orders/new.html.erb
<h1>Place an order</h1>

<%= render "form", order: @order %>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>

<div>
  <%= link_to "Edit this order", edit_order_path(@order) %> |
  <%= link_to "Back to orders", orders_path %>
</div>